### PR TITLE
Change parent to jclouds-project to decouple from aggregator pom

### PR DESCRIPTION
**Pull request by nacx**
Let's see if this fixes pom plugin config inheritance

### CODE REVIEW

**Comment by nacx** [comment]
Hmmm I don't get why it is passing when I run it locally. @demobox, @gaul any hints?

**Comment by demobox** [comment]
> @demobox, @gaul any hints?

Silly question: Maven version, perhaps? I looked at the [`jclouds-project` POM](https://repository.apache.org/content/repositories/snapshots/org/apache/jclouds/jclouds-project/2.2.0-SNAPSHOT/jclouds-project-2.2.0-20190618.101004-131.pom) the build apparently used, and that seemed OK.

Even if we get this to pass, we should check that Javadoc generation and releasing still work - those were two things, from what I recall, that broke during past attempts at parent/aggregator switches.

**Comment by demobox** [comment]
Hrm...this is the error message:
```
Found duplicate (but equal) classes in [org.apache.jclouds:jclouds-core:2.2.0-20190618.101351-130, org.apache.jclouds:jclouds-gson:2.2.0-20190618.101050-2]
```
The configuration in the POM is:
```
<dependency>
<groupId>org.apache.jclouds</groupId>
<artifactId>jclouds-core</artifactId>
<version>${project.version}</version>
</dependency>
<dependency>
<groupId>org.apache.jclouds</groupId>
<artifactId>jclouds-gson</artifactId>
<version>${project.version}</version>
</dependency>
```
I wonder if it's tripping up over `${project.version}` vs. the resolved versions? Can we remove `${project.version}` to see if that fixes it?

If you run it locally with the duplicate-finder exception commented out, what are the version numbers it reports for the conflicting packages?

**Comment by nacx** [comment]
Removing the version seems to fix it. I'll push the build to master and monitor the labs build. If ti works I'll close this PR. Thanks!

**Comment by nacx** [comment]
Your suggested fix fixed the build, so I'm closing this. Thx!

**Pull request closed without merging**
