### PR TITLE
Remove JDBC provider

### PR DESCRIPTION
**Pull request by gaul**
This was written in a confusing way, storing both metadata and data in
a SQL database, making it only useful for testing which duplicates the
existing transient provider.  It has no known users and creates a
maintenance burden.

### CODE REVIEW

**Review by nacx — APPROVED** [review]

**Comment by yhilem** [comment]
Hi, 
Please can you revert changes?
I have started design & implementation of our S3 Service with this JDBC implementation.
- https://github.com/linkedin/ambry/issues/555#issuecomment-466646681
- https://github.com/linkedin/ambry/issues/555#issuecomment-466749576
- https://github.com/linkedin/ambry/issues/555#issuecomment-467327633

Thanks
Youcef HILEM

**Comment by gaul** [comment]
@yhilem could you explain your use case and how the old JDBC provider addresses it?  The previous JPA approach was hard for us to maintain and created a maintenance burden when changing other parts of jclouds.  I think a SQL provider has merit and could actually replace the existing transient and filesystem providers if written in a different way, e.g., raw JDBC.  This is a modest amount of work, perhaps 1-2 weeks.

Note that you don't need jclouds to revert this to use the provider.  Another alternative is creating a fork of the old code and adding the dependency to your project.

**Comment by yhilem** [comment]
Thank you for your response.

For jclouds-jdbc I started use DataNucleus JPA with Cassandra [1].
But all the tests fail [2].
[1] https://github.com/datanucleus/datanucleus-cassandra/issues/33#issuecomment-473534351
[2] https://github.com/datanucleus/datanucleus-cassandra/issues/34

Actually, we want to use Cassandra as a backend.
We have tested and validated the Pithos (https://github.com/exoscale/pithos) solution, but we are looking to migrate to a more recent implementation based on Cassandra, like (https://github.com/mindmill/ladon-s3-cassandra) but OpenSource.

But, I completely agree on the usefulness of a SQL provider with raw JDBC.
In this case I will look rather towards a backend with YugaByteDB or TiDB.

Anyway, our S3Gateway is an evolution of S3Proxy (https://github.com/gaul/s3proxy) with integration of:
- OPA Sidecar [3, 4] : After a user is authenticated, OPA can be used to check if the user is authorized to perform the given action on the resource. OPA responds with an allow or deny decision which is sent back to the RGW which enforces the decision.
- Security Token Service (STS) (https://github.com/minio/minio/tree/master/docs/sts)

Panama (S3Prox++) - STS
Panama (S3Prox++) - OPA

[3, 4, 5]
- https://docs.ceph.com/docs/master/radosgw/opa/
- https://www.openpolicyagent.org/docs/latest/comparison-to-other-systems/#amazon-web-services-iam

**Comment by gaul** [comment]
@yhilem This seems reasonable.  I believe that you can use an older version of jclouds with S3Proxy for now and experiment with the JDBC provider from the 2.1.2 release.  After you have some experience with this, probably after a few months, please open an issue and we can discuss either the re-inclusion of the old provider or some other path forward.  Note that you will likely need to do much of the heavy lifting with regard to bug fixes -- previously I did this work and was not able to satisfactorily track changes from jclouds core.

**Comment by yhilem** [comment]
Thany you. 
I'll be back as soon as I finish all the tests.

**Pull request merged**
